name:                regmgr
version:             0.1.0.0
github:              "githubuser/regmgr"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/regmgr#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - network
  - postgresql-simple
  - yaml


executables:
  regmgr-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - regmgr
    - aeson
    - blaze-html
    - bytestring
    - cassava
    - digestive-functors
    - digestive-functors-blaze
    - generics-sop
    - HaskellNet
    - HaskellNet-SSL
    - mime-mail
    - network
    - postgresql-simple
    - postgresql-simple-sop
    - process
    - servant
    - servant-server
    - servant-blaze
    - servant-cassava
    - text
    - uuid
    - warp
    - yaml
  regmgr-from-osm:
    main: Main.hs
    source-dirs: from-osm
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - regmgr
    - postgresql-simple
    - random
    - uuid
    - text

tests:
  regmgr-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - regmgr
