ALTER TABLE regmgr_attendee ADD COLUMN remedy_paracetamol BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE regmgr_attendee ADD COLUMN remedy_piriton BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE regmgr_attendee ADD COLUMN remedy_ibuprofen BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE regmgr_attendee ADD COLUMN remedy_waspeze BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE regmgr_attendee ADD COLUMN remedy_anthisan BOOLEAN DEFAULT FALSE NOT NULL;
